TravelSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from TravelSystem import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('area/', include("area.urls", namespace="area")),
    path('article/', include("article.urls", namespace="article")),
    path('comment/', include('common_comment.urls', namespace="comment")),
    path('forum/', include('forum.urls', namespace='forum')),
    path('user/', include('user.urls', namespace='user')),
    path('', include('travel.urls', namespace='travel')),
    path('upload_image/', views.upload_image),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

area/urls.py
from django.urls import path
from . import views

app_name = "area"

urlpatterns = [
    path('province-autocomplete/', views.ProvinceAutocomplete.as_view(), name='province-autocomplete'),
    path('city-autocomplete/', views.CityAutocomplete.as_view(), name='city-autocomplete'),
]

article/urls.py
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('article_detail/<pk>', views.ArticleDetail.as_view(), name="article_detail"),
    path('special_cate_article/<pk>', views.SpecialCateArticle.as_view(), name="special_cate_article"),
    path('special_tag_article/<pk>', views.SpecialTagArticle.as_view(), name="special_tag_article"),
    path('search_article/', views.SearchArticle.as_view(), name="search_article"),
    path('publish_article/', views.PublishArticle.as_view(), name="publish_article"),

    path("chart_view/", views.chart_view, name="chart_view"),
    path("cate_articles_per/", views.cate_articles_per, name="cate_articles_per"),
    path("article_views_rank/", views.article_views_rank, name="article_views_rank"),

]

common_comment/urls.py
from django.urls import path
from . import views

app_name = "common_comment"

urlpatterns = [
    path("post-comment/", views.post_comment, name="post_comment"),
    path("post-comment/<int:parent_comment_id>", views.post_comment, name="reply_comment"),
]

forum/urls.py
from django.urls import path, include
from .views import *

app_name = "post"

urlpatterns = [

    path("", IndexView.as_view(), name="index"),
    path("search/", SearchView.as_view(), name="search"),
    path("hot_post/", HotPostView.as_view(), name="hot_post"),
    path("cate_list/", CateList.as_view(), name="cate_list"),
    path("add_post/", AddPost.as_view(), name="add_post"),
    path("cate_post/", CatePost.as_view(), name="cate_post"),
    path("detail/<int:pk>", PostDetail.as_view(), name="detail"),
    path("user_author_view_follow/<author_id>", user_author_view_follow, name="user_author_view_follow"),
    path("author_detail/", AuthorDetail.as_view(), name="author_detail"),
    path("user_follow/<author_id>/<object_pk>", user_follow, name="user_follow"),
    path("user_thumb_up/", user_thumb_up, name="user_thumb_up"),
    path("user_thumb_down/", user_thumb_down, name="user_thumb_down"),


]

travel/urls.py
from django.urls import path
from . import views

app_name = "travel"

urlpatterns = [
    path('attraction_detail/<int:pk>/', views.AttractionDetailView.as_view(), name='attraction_detail'),
    path('attraction_favorite/<int:pk>/', views.attraction_toggle_favorite, name='attraction_toggle_favorite'),
    path('attraction_visited/<int:pk>/', views.attraction_toggle_visited, name='attraction_toggle_visited'),
    path('tourpackage_detail/<int:pk>/', views.TourPackageDetailView.as_view(), name='tourpackage_detail'),
    path('tourpackage_favorite/<int:pk>/', views.toggle_tour_package_favorite, name='tourpackage_favorite'),
    path('submit_order/<int:pk>/', views.SubmitOrderView.as_view(), name='submit_order'),

    path('', views.AttractionListView.as_view(), name='attraction_list'),
    path('attraction_search/', views.AttractionSearchView.as_view(), name='attraction_search'),
    path('attraction_my_favorite/', views.MyFavoriteAttraction.as_view(), name='attraction_my_favorite'),
    path('attraction_my_visited/', views.MyVisitedAttraction.as_view(), name='attraction_my_visited'),

    path('tour_package_list/', views.TourPackageListView.as_view(), name='tour_package_list'),
    path('tour_package_search/', views.TourPackageSearchView.as_view(), name='tour_package_search'),
    path('tour_package_my_favorite/', views.MyFavoriteTourPackage.as_view(), name='tour_package_my_favorite'),
    path('my_order/', views.MyOrderView.as_view(), name='my_order'),
]

user/urls.py
from django.urls import path
from . import views
app_name = "user"

urlpatterns = [
    path('user_register/', views.user_register, name='user_register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_password/', views.user_password, name='user_password'),
    path('user_profile_view/', views.user_profile_view, name='user_profile_view'),
    path('user_profile_create/', views.user_profile_create, name='user_profile_create'),
    path('user_profile_update/<int:pk>', views.UserProfileUpdate.as_view(), name='user_profile_update'),
    path('test_page/', views.text_page, name="test_page")
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include 'components/css_file.html' %}

    <style>
        .asteriskField {
            display: none;
        }

        a {
            color: #6984c2;
            text-decoration: none;
            background-color: transparent;
        }

        a:hover {
            color: #405d9e;
            text-decoration: none;
        }
    </style>
    {% block page_style %} {% endblock %}
</head>
<body>

<div style="min-height: 100vh; display: flex; flex-direction: column">
    <div style="flex-grow: 1;">
        {% include 'components/navbar.html' %}

        {% block article_base %}
        {% endblock %}

        {% block forum_base %}
        {% endblock %}

        {% block user_base %}
        {% endblock %}

        {% block travel_base %}
        {% endblock %}
    </div>
    {% include 'components/footer.html' %}
</div>


{% include 'components/js_file.html' %}
{% block page_js %} {% endblock %}
<script>
    $(document).ready(function () {
        const datePicker = MCDatepicker.create({
            el: '#mc_date_picker',
            bodyType: 'modal',
            customClearBTN: '清除',
            customCancelBTN: '取消',
            customOkBTN: '确认',
            selectedDate: new Date(),
            dateFormat: 'yyyy-mm-dd',
            customWeekDays: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
            customMonths: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
        });
        $('.select2-example').select2({
            language: "zh-CN"
        });
    });
</script>
</body>
</html>

templates/components/card_content.html
{% extends 'base.html' %}
{% block content %}
    <div class="row row-cols-xl-4 row-cols-lg-3 row-cols-md-2 row-cols-1 g-3 mt-2">
        {% for object in object_list %}
            <div class="col">
                <div class="card">
                    <img src="{{ object.book_cover_thumbnail.url }}" class="img-responsive card-img-top">
                    <div class="card-body">
                        <h5 class="card-title mb-1">{{ object.name }}</h5>
                        <p class="card-text mt-0 mb-1">{{ object.address }}</p>
                        <a href="{% url 'test:book_detail' object.pk %}" class="btn btn-primary btn-sm">
                            详情
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/components/create_object.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row">
        <div class="col-8 offset-2">
            <h3 class="text-center">{{ title }}</h3>
            <hr>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary">
                <input type="reset" class="btn btn-danger">
            </form>
        </div>
    </div>
{% endblock %}

templates/components/css_file.html
{% load static %}

<!--导入Bootstrap5-->
<link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.css' %}">

<!--导入Bootstrap的图标库-->
<link rel="stylesheet" href="{% static 'bootstrap-icons/bootstrap-icons.css' %}">

<!--导入sweetalert，一个漂亮的alert插件-->
<link rel="stylesheet" href="{% static 'sweetalert/sweetalert2.css' %}">

<!--导入mc-calendar，一个漂亮的日期插件-->
<link rel="stylesheet" href="{% static 'mc_calendar/mc-calendar.min.css' %}">

<!--一个日期时间插件，该插件依赖于jquery-->
<link rel="stylesheet" href="{% static 'datetimepicker/jquery.datetimepicker.css' %}">

<!--一个特别好用的图标图-->
<link rel="stylesheet" href="{% static 'fontawesome4/css/font-awesome.css' %}">
<link rel="stylesheet" href="{% static 'fontawesome6/css/all.css' %}">

<!--一个好用的select插件-->
<link rel="stylesheet" href="{% static 'select2-bootstrap/css/select2.min.css' %}">
<!--这个是针对bootstrap4的-->
{% comment %}<link rel="stylesheet" href="{% static 'select2-bootstrap/bootstrap/select2-bootstrap4.min.css' %}">{% endcomment %}
<!--这个是针对bootstrap5的-->
<link rel="stylesheet" href="{% static 'select2-bootstrap/bootstrap/select2-bootstrap-5-theme.min.css' %}">

<!--一个好用的时间插件，结合后端的form配置，可以很灵活的进行配置-->
<link rel="stylesheet" href="/static/flatpickr/flatpickr.min.css">
<link rel="stylesheet" href="/static/flatpickr/themes/material_red.css">

templates/components/footer.html
<style>
    .footer {
        background: linear-gradient(to right, #1a1c20, #2c3e50);
        color: #ffffff;
        padding: 70px 0 30px;
        {% comment %}position: relative;
        overflow: hidden;{% endcomment %}

    }

    .footer::before {
        content: '';
        {% comment %}position: absolute;{% endcomment %}
        top: 0;
        left: 0;
        right: 0;
        height: 3px;
        background: linear-gradient(to right, #3498db, #2ecc71);
    }

    .footer-logo {
        font-size: 1.8rem;
        font-weight: 700;
        margin-bottom: 20px;
        background: linear-gradient(45deg, #3498db, #2ecc71);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }

    .footer-about {
        color: #a4b5c6;
        margin-bottom: 25px;
        line-height: 1.6;
    }

    .footer h5 {
        color: #ffffff;
        font-weight: 600;
        margin-bottom: 25px;
        position: relative;
    }

    .footer h5::after {
        content: '';
        position: absolute;
        left: 0;
        bottom: -10px;
        width: 30px;
        height: 2px;
        background: #3498db;
    }

    .footer-links {
        list-style: none;
        padding: 0;
        margin: 0;
    }

    .footer-links li {
        margin-bottom: 12px;
    }

    .footer-links a {
        color: #a4b5c6;
        text-decoration: none;
        transition: all 0.3s ease;
        display: inline-block;
    }

    .footer-links a:hover {
        color: #3498db;
        transform: translateX(5px);
    }

    .social-links {
        display: flex;
        gap: 15px;
        margin-top: 20px;
    }

    .social-icon {
        width: 35px;
        height: 35px;
        background: rgba(255, 255, 255, 0.1);
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #fff;
        text-decoration: none;
        transition: all 0.3s ease;
    }

    .social-icon:hover {
        background: #3498db;
        transform: translateY(-3px);
        color: #fff;
    }

    .footer-newsletter {
        position: relative;
        margin-top: 20px;
    }

    .footer-newsletter input {
        padding: 12px 15px;
        border-radius: 25px;
        border: none;
        width: 100%;
        background: rgba(255, 255, 255, 0.1);
        color: #fff;
        outline: none;
        padding-right: 50px;
    }

    .footer-newsletter input::placeholder {
        color: #a4b5c6;
    }

    .newsletter-btn {
        position: absolute;
        right: 5px;
        top: 5px;
        bottom: 5px;
        width: 40px;
        border-radius: 50%;
        background: #3498db;
        border: none;
        color: #fff;
        transition: all 0.3s ease;
    }

    .newsletter-btn:hover {
        background: #2980b9;
    }

    .footer-bottom {
        margin-top: 50px;
        padding-top: 20px;
        border-top: 1px solid rgba(255, 255, 255, 0.1);
        text-align: center;
        color: #a4b5c6;
    }

    .footer-bottom-links {
        list-style: none;
        padding: 0;
        margin: 15px 0;
        display: flex;
        justify-content: center;
        gap: 20px;
    }

    .footer-bottom-links a {
        color: #a4b5c6;
        text-decoration: none;
        transition: color 0.3s ease;
    }

    .footer-bottom-links a:hover {
        color: #3498db;
    }

    @media (max-width: 768px) {
        .footer-section {
            margin-bottom: 40px;
        }
    }
</style>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 footer-section">
                <div class="footer-logo">旅游系统</div>
                <p class="footer-about">本项目是基于Python语言的Django网络框架实现的旅游系统。主要功能：景点、旅游包、论坛管理、图表分析、旅游心得、密码修改等功能。</p>
                <div class="social-links">
                    <a href="#" class="social-icon"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="social-icon"><i class="fab fa-twitter"></i></a>
                    <a href="#" class="social-icon"><i class="fab fa-instagram"></i></a>
                    <a href="#" class="social-icon"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>

            <div class="col-lg-2 col-md-6 footer-section">
                <h5>旅游链接</h5>
                <ul class="footer-links">
                    <li><a href="{% url 'travel:attraction_list' %}">所有景点</a></li>
                    <li><a href="{% url 'travel:tour_package_list' %}">所有旅游包</a></li>
                    <li><a href="{% url 'article:index' %}">旅游攻略</a></li>
                    <li><a href="{% url 'forum:index' %}">旅游论坛</a></li>
                </ul>
            </div>

            <div class="col-lg-2 col-md-6 footer-section">
                <h5>用户信息</h5>
                <ul class="footer-links">
                    <li><a href="{% url 'user:user_profile_view' %}">个人信息</a></li>
                    <li><a href="{% url 'user:user_password' %}">密码修改</a></li>
                    <li><a href="{% url 'travel:my_order' %}">我的订单</a></li>

                </ul>
            </div>

            <div class="col-lg-4 footer-section">
                <h5>待开发...</h5>
                <p class="footer-about">Subscribe to our newsletter for updates, news, and exclusive offers.</p>
                <div class="footer-newsletter">
                    <input type="email" placeholder="Enter your email">
                    <button class="newsletter-btn">
                        <i class="fas fa-paper-plane"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/components/index_content_card.html
<div class="row row-cols-1 row-cols-md-4 g-4 mt-2">
    {% for object in books %}
        <div class="col">
            <div class="card">
                <img src="{{ object.thumbnail.url }}" class="img-responsive card-img-top" height="220px">
                <div class="card-body">
                    <h5 class="card-title">{{ object.name }}</h5>
                    <span class="mt-0 d-block">
                        作者：{{ object.author }}
                    </span>
                    <span class="mt-0 d-block">
                        出版社：{{ object.publish_house }}
                    </span>
                    <span class="mb-2 d-block">
                        出版时间：{{ object.publish_date }}
                    </span>
                    <a href="{% url 'book:book_detail' object.pk %}" class="btn btn-primary">详情</a>
                    <a data-value="{{ object.pk }}" class="btn btn-warning book_borrow_btn">借阅</a>
                </div>
            </div>
        </div>
    {% endfor %}
    {% block page_js %}

    {% endblock %}

</div>

templates/components/js_file.html
{% load static %}

<!--导入jquery-->
<script type="text/javascript" src="{% static 'jquery/jquery3.6.js' %}"></script>

{% comment %}<!--导入Bootstrap3-->
<script type="text/javascript" src="{% static 'bootstrap3/bootstrap.js' %}"></script>

<!--导入Bootstrap4-->
<script type="text/javascript" src="{% static 'bootstrap4/bootstrap.bundle.js' %}"></script>{% endcomment %}

<!--导入Bootstrap5-->
<script type="text/javascript" src="{% static 'bootstrap5/bootstrap.bundle.js' %}"></script>

{% comment %}<script type="text/javascript" src="{% static 'mdb/mdb.min.js' %}"></script>{% endcomment %}

<!--导入sweetalert，一个漂亮的alert插件-->
<script type="text/javascript" src="{% static 'sweetalert/sweetalert2.all.js' %}"></script>

<!--导入mc-calendar，一个漂亮的日期插件-->
<script type="text/javascript" src="{% static 'mc_calendar/mc-calendar.min.js' %}"></script>

<!--一个日期时间插件，该插件依赖于jquery-->
<script type="text/javascript" src="{% static 'datetimepicker/jquery.datetimepicker.js' %}"></script>


<script type="text/javascript" src="{% static 'echarts/main.js' %}"></script>

<!--一个好用的select插件-->
<script type="text/javascript" src="{% static 'select2-bootstrap/js/select2.full.js' %}"></script>

templates/components/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark "
     style="padding-bottom: 0.1rem; padding-top: 0.1rem; background-color: #3b4348">
    <div class="container">
        <a class="navbar-brand" href="#">旅游系统</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'travel:attraction_list' %}">景点</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'travel:tour_package_list' %}">旅行包</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown">
                        旅游攻略
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'article:index' %}">攻略详情</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'article:publish_article' %}">发布攻略</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'article:chart_view' %}">攻略分析</a></li>
                    </ul>
                </li>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown">
                        在线论坛
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'forum:index' %}">论坛首页</a></li>
                        <li><a class="dropdown-item" href="{% url 'forum:cate_list' %}">模块分类</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'forum:add_post' %}">发布帖子</a></li>
                    </ul>
                </li>

            </ul>
            <div class="d-flex ">
                <ul class="nav justify-content-center align-items-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'travel:attraction_my_visited' %}">旅游足迹</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'travel:attraction_my_favorite' %}">景点收藏</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'travel:tour_package_my_favorite' %}">旅行包收藏</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'travel:my_order' %}">我的订单</a>
                    </li>
                    {% if user.is_authenticated %}
                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown">
                                <img src="{{ user.user_profile.avatar.url }}" alt="hello" width="32" height="32"
                                     class="rounded-circle">
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'user:user_profile_view' %}">个人信息</a></li>
                                <li><a class="dropdown-item" href="{% url 'user:user_password' %}">重置密码</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'user:user_logout' %}">退出系统</a></li>
                            </ul>
                        </div>
                    {% else %}
                        <div class="d-flex">
                            <a href="{% url 'user:user_login' %}" class="btn btn-sm btn-success me-2">
                                登录
                            </a>
                            <a href="{% url 'user:user_register' %}" class="btn btn-sm btn-warning">
                                注册
                            </a>
                        </div>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>

templates/components/paginator.html
{% if is_paginated %}
    <nav class="text-center d-flex justify-content-center mt-4">
        <ul class="pagination">

            {# 上一页 #}
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?{% if query_params %}{{ query_params.urlencode }}&{% endif %}page={{ page_obj.previous_page_number }}">
                        上一页
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">上一页</a></li>
            {% endif %}

            {# 左侧省略号 + 数字 #}
            {% if left_more_page %}
                <li class="page-item"><a class="page-link" href="?{% if query_params %}{{ query_params.urlencode }}&{% endif %}page=1">1</a></li>
                <li class="page-item"><a class="page-link" href="#">…</a></li>
            {% endif %}

            {% for lp in left_range %}
                <li class="page-item"><a class="page-link" href="?{% if query_params %}{{ query_params.urlencode }}&{% endif %}page={{ lp }}">{{ lp }}</a>
                </li>
            {% endfor %}

            {# 当前页 #}
            <li class="page-item active">
                <a class="page-link" href="?{% if query_params %}{{ query_params.urlencode }}&{% endif %}page={{ page_obj.number }}">{{ page_obj.number }}</a>
            </li>

            {% for rp in right_range %}
                <li class="page-item"><a class="page-link" href="?{% if query_params %}{{ query_params.urlencode }}&{% endif %}page={{ rp }}">{{ rp }}</a>
                </li>
            {% endfor %}

            {# 右侧省略号 + 尾页 #}
            {% if right_more_page %}
                <li class="page-item"><a class="page-link" href="#">…</a></li>
                <li class="page-item"><a class="page-link" href="?{% if query_params %}{{ query_params.urlencode }}&{% endif %}page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                </li>
            {% endif %}

            {# 下一页 #}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{% if query_params %}{{ query_params.urlencode }}&{% endif %}page={{ page_obj.next_page_number }}">
                        下一页
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">下一页</a></li>
            {% endif %}

        </ul>
    </nav>
{% endif %}

templates/components/pro_city.html
<form>
    <label for="province">省份：</label>
    <select id="province">
        <option value="">请选择省份</option>
    </select>

    <label for="city">城市：</label>
    <select id="city">
        <option value="">请选择城市</option>
    </select>

    <label for="district">区县：</label>
    <select id="district">
        <option value="">请选择区县</option>
    </select>
</form>

templates/sidebar/cate_tag_sidebar.html
{% load post_tags %}
<div class="card" style="">
    <div class="card-header text-center h4">
        所有分类
    </div>
    <ul class="list-group list-group-flush">
        {% all_category_tag as all_cates  %}
        {% for cate in all_cates %}
            <li class="list-group-item d-flex justify-content-between">
                <span>
                    {{ cate.name }}
                </span>
                <span>
                    {{ cate.cate_total }}
                </span>
            </li>
        {% endfor %}
    </ul>
</div>

templates/sidebar/cate_tag_sidebar_img.html
{% load post_tags %}
<div class="card" style="">
    <div class="card-header text-center h4">
        所有分类
    </div>
    <ul class="list-group list-group-flush">
        {% all_category_tag as all_cates  %}
        {% for cate in all_cates %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <img src="{{ cate.avatar_thumbnail.url }}" alt="分类缩略图" >
                    <span class="ms-2">
                        {{ cate.name }}
                    </span>
                </div>

                <span>
                    {{ cate.cate_total }}
                </span>
            </li>
        {% endfor %}
    </ul>
</div>

templates/sidebar/siderbar.html
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32">
            <use xlink:href="#bootstrap" />
        </svg>
        <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="#" class="nav-link active" aria-current="page">
                <svg class="bi me-2" width="16" height="16">
                    <use xlink:href="#home" />
                </svg>
                Home
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16">
                    <use xlink:href="#speedometer2" />
                </svg>
                Dashboard
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16">
                    <use xlink:href="#table" />
                </svg>
                Orders
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16">
                    <use xlink:href="#grid" />
                </svg>
                Products
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16">
                    <use xlink:href="#people-circle" />
                </svg>
                Customers
            </a>
        </li>
    </ul>
    <hr>
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
            id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>mdo</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
    </div>
</div>